  - name: Add VLANs
    ios_config:
      lines:
      - name {{ vlans.data_name }}
      parents:
      - vlan {{ vlan }}

  - name: Configure interface settings
    ios_config:
      lines:
        - description Voice+Data
        - switchport access vlan {{ vlans.data }}
        - spanning-tree portfast
      parents: interface range Gi1/0/1-22

  - name: Create port-channel
    ios_config:
      lines:
        - no switchport
        - channel-group 12 mode active
      parents: interface range Gi1/0/23-24
      
  - name: Configure port-channel
    ios_config:
      lines:
        - ip address {{ ip.port-channel }}
        - channel-group 12 mode active
        - ip authentication mode eigrp 100 md5
        - ip authentication key-chain eigrp 100 cisco
      parents: interface port-channel 12
      
  - name: Configure routing
    ios_config:
      lines:
        - network {{ ip.eigrp }}
        - channel-group 12 mode active
      parents: router eigrp 100
     
