---
- name: Create GLBP Template
  template: src=glbp.j2 dest=/etc/ansible/configs/{{ item.description }}.cfg
  with_items:
  - "{{ Bld }}"

- name: Compile GLBP configs
  assemble: src=/etc/ansible/configs/ dest=/etc/ansible/finalconfigs/GLBP_FINAL.cfg

  - name: Configure VTP Mode
    ios_config:
      lines:
        - vtp mode transparent

  - name: Configure Spanning-Tree
    ios_config:
      lines:
        - spanning-tree mode rapid-pvst
        - spanning-tree portfast bpduguard default
        - spanning-tree extend system-id

  - name: Shutdown VLAN 1
    ios_config:
      lines:
        - no ip address
        - shutdown
      parents: interface vlan 1

  - name: Add SNMP_V3 ACL
    ios_config:
      lines:
      - permit host 192.168.100.50'
      - deny any log
      parents:
      - ip access-list standard SNMPV3_ACCESS
      
  - name: Configure Err-disable Recovery
    ios_config:
      lines:
        - errdisable recovery cause udld
        - errdisable recovery cause channel-misconfig
        - errdisable recovery cause psecure-violation
        - errdisable recovery cause dhcp-rate-limit

  - name: Configure Services
    ios_config:
      lines:
        - service nagle
        - no service pad
        - service tcp-keepalives-in
        - service tcp-keepalives-out
        - service timestamps debug datetime msec localtime show-timezone
        - service timestamps log datetime msec localtime show-timezone
        - service password-encryption

  - name: Configure SNMP
    ios_config:
      lines:
        - snmp-server user cisco_user cisco_group v3 auth md5 cisco priv aes 128 cisco access SNMPV3_ACCESS
        - snmp-server group cisco_group v3 priv access SNMPV3_ACCESS
        - snmp-server view SNMPV3_READ iso included
        - snmp-server location Lake Oswego
        - snmp-server contact HELPDESK
        - snmp-server enable traps syslog

  - name: Configure NTP
    ios_config:
      lines:
        - clock timezone PST -8
        - clock summer-time PDT recurring
        - ntp server 192.168.200.10 prefer
        - ntp server 192.168.200.11

  - name: Configure Syslog
    ios_config:
      lines:
        - logging trap debugging
        - logging 192.168.100.50

  - name: Misc
    ios_config:
      lines:
        - ip tcp selective-ack
        - no ip http server
        - no ip http secure-server
        - no ip domain-lookup
