---
- name: Configure VTP Mode
  ios_config:
    lines:
      - vtp mode transparent
  tags: vtp
  
- name: Configure Spanning-Tree
  ios_config:
    lines:
      - spanning-tree mode rapid-pvst
      - spanning-tree portfast bpduguard default
      - spanning-tree extend system-i
  tags: spanning-tree
  
- name: Shutdown VLAN 1
  ios_config:
    lines:
      - no ip address
      - shutdown
    parents: interface vlan 1
  tags: default_vlan

- name: Add SNMP_V3 ACL
  ios_config:
    lines:
    - permit host 192.168.100.50
    - deny any log
    parents:
    - ip access-list standard SNMPV3_ACCESS
  tags: acl
  
- name: Add VLANs
  ios_config:
    lines:
      - name {{ vlan_name }}
    parents:
      - vlan {{ vlan }}

- name: Configure interface settings
  ios_config:
    lines:
      - description Voice+Data
      - switchport access vlan {{ vlan }}
      - spanning-tree portfast
    parents: interface range Gi1/0/1-22

- name: Create port-channel
  ios_config:
    lines:
      - no switchport
      - channel-group 12 mode active
    parents: interface range Gi1/0/23-24

- name: Configure port-channel
  ios_config:
    lines:
      - ip address {{ lag_ip }}
      - channel-group 12 mode active
    parents: interface port-channel 12

- name: Configure routing
  ios_config:
    lines:
      - network {{ lag_eigrp }}
      - network {{ svi_eigrp }}
      parents: router eigrp 100
      
- name: Configure Err-disable Recovery
  ios_config:
    lines:
      - errdisable recovery cause udld
      - errdisable recovery cause channel-misconfig
      - errdisable recovery cause psecure-violation
      - errdisable recovery cause dhcp-rate-limit
  tags: errdisable
  
- name: Configure Services
  ios_config:
    lines:
      - service nagle
      - no service pad
      - service tcp-keepalives-in
      - service tcp-keepalives-out
      - service timestamps debug datetime msec localtime show-timezone
      - service timestamps log datetime msec localtime show-timezone
      - service password-encryption
  tags: services
  
- name: Configure SNMP
  ios_config:
    lines:
      - snmp-server user cisco_user cisco_group v3 auth md5 cisco priv aes 128 cisco access SNMPV3_ACCESS
      - snmp-server group cisco_group v3 priv access SNMPV3_ACCESS
      - snmp-server view SNMPV3_READ iso included
      - snmp-server location Lake Oswego
      - snmp-server contact HELPDESK
      - snmp-server enable traps syslo
  tags: snmp
  
- name: Configure NTP
  ios_config:
    lines:
      - clock timezone PST -8
      - clock summer-time PDT recurring
      - ntp server 192.168.200.10 prefer
      - ntp server 192.168.200.1
  tags: ntp
  
- name: Configure Syslog
  ios_config:
    lines:
      - logging trap debugging
      - logging 192.168.100.5
  tags: syslog
  
- name: Misc
  ios_config:
    lines:
      - ip tcp selective-ack
      - no ip http server
      - no ip http secure-server
      - no ip domain-lookup
  tags: misc

