---
- name: Save Running Config
  hosts: c9300_UP_lab
  connection: network_cli

  tasks:

  - name: Show running-config
    ios_command:
      commands:
        - show run
    register: config

  - copy:
      content: "{{ config.stdout[0] }}"
      dest: "/var/ansible/backups/{{ inventory_hostname }}.txt"
...
