---
- name: Save Running Config
  hosts: Demo_SW_1
  connection: network_cli

  tasks:

  - name: Get hostname
    ios_command:
      commands:
        - show run | i hostname
    register: hostname

  - name: Show running-config
    ios_command:
      commands:
        - show run
    register: config

  - copy:
      content: "{{ config.stdout[0] }}"
      dest: "/var/ansible/backups/{{ hostname.stdout[0] }}.txt"
...
