---
- name: Generate roles config
  hosts: Demo_SW_1
  gather_facts: no
  connection: network_cli
  
  tasks:
  
  - name: Add VLANs
    ios_config:
      lines:
        - name {{ item.vlan_name }}  
      parents:
        - vlan {{ item.vlan }}
    with_items: "{{ demo_sw }}"

  - name: Configure interface settings
    ios_config:
      lines:
        - description Voice+Data
        - switchport access vlan {{ item.vlan }}
        - spanning-tree portfast
      parents: interface range Gi1/0/1-22
    with_items: "{{ demo_sw }}"
...
