---
- name: Generate roles config
  hosts: c9300_UP_lab1
  gather_facts: no
  connection: network_cli
  
  tasks:
  
  - name: Add VLANs
    ios_config:
      lines:
        - name {{ vlan_name }}  
      parents:
        - vlan {{ vlan }}

  - name: Configure interface settings
    ios_config:
      lines:
        - description Voice+Data
        - switchport access vlan {{ vlan }}
        - spanning-tree portfast
      parents: interface range Gi1/0/1-22
...
