---
- name: Generate NTP config
  hosts: c9300_UP_lab
  gather_facts: no
  connection: network_cli
  
  tasks:
  
  - name: Configure NTP
    ios_config:
      lines:
        - clock timezone PST -8
        - clock summer-time PDT recurring
        - ntp server 192.168.200.10 prefer
        - ntp server 192.168.200.1
...
