---
- name: Generate syslog config
  hosts: c9300_UP_lab
  gather_facts: no
  connection: network_cli

  tasks:

  - name: Configure Syslog
    ios_config:
      lines:
        - logging trap debugging
        - logging 192.168.100.5
    tags: syslog
...
